// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYG_I5DAHwX30te2dEJ4K-2bvaR71JKW8',
    appId: '1:890549645315:android:17976bd6c3c7cc17b55e36',
    messagingSenderId: '890549645315',
    projectId: 'jobportal-f1613',
    storageBucket: 'jobportal-f1613.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtrwtuoK8LAksmcQiYkWhJ-6jY2jqReng',
    appId: '1:890549645315:ios:f88ea7d8b7e9dd71b55e36',
    messagingSenderId: '890549645315',
    projectId: 'jobportal-f1613',
    storageBucket: 'jobportal-f1613.appspot.com',
    androidClientId: '890549645315-ue6amp9saupeti3c6f6folc3q5cpbmku.apps.googleusercontent.com',
    iosClientId: '890549645315-udbdvrtp6q6g5jjonai6057atl2aic8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobPortal.RunnerTests',
  );

}